version: 1.0.{build}

skip_tags: true

environment:
  matrix:
    - RUBY_VERSION: "22-x64"
    - RUBY_VERSION: "22"
    - RUBY_VERSION: "24-x64"
    - RUBY_VERSION: "24"

install:
  - nuget install NUnit -Version 2.6.4
  - nuget install NUnit.Runners -Version 2.6.4
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install hiptest-publisher
  - hiptest-publisher -c nunit.conf --token=$SECRET_TOKEN --only=tests --test-run-id=9861

build: off
