version: 1.0.{build}

skip_tags: true

environment:
  matrix:
    - RUBY_VERSION: "24"
  SECRET_TOKEN:
    secure: LTq33sBzoy1aaeUFoKbV/Na1u0PO/IUDVxOQdz+taXgZ1Qv1OfmKYwID8td3owSOJ5tBWRgztdLySruyXaMOCg==

before_build:
  - nuget install NUnit -Version 2.6.4
  - nuget install NUnit.Runners -Version 2.6.4

build:
  include_nuget_references: true

# install:
#   - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
#   - gem install hiptest-publisher

# before_build:
#   - nuget restore

# before_test:
#   - hiptest-publisher -c nunit.conf --token=%SECRET_TOKEN% --only=tests --test-run-id=9861

# test:
#   assemblies:
#     - '**\*.Test.dll'

after_test:
  - type TestResult.xml
#   - hiptest-publisher -c nunit.conf --token=%SECRET_TOKEN% --push=TestResult.xml --test-run-id=9861
